package = "rjieba"
version = "0.0.3"
lua = ">= 5.1"

[description]
summary = "lua binding for jieba-rs"
detailed = ""
maintainer = "Wu"
labels = ["neovim"]
homepage = "https://github.com/neo451/jieba-lua/tree/master/packages/rjieba"
license = 'MIT'

[source]
url = "https://github.com/neo451/jieba-lua/archive/$(VERSION).zip"
dir = "jieba-lua-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
"wordmotion.nvim" = " >= 0.0.1"

[test]
type = "busted"

[build]
type = "rust-mlua"
copy_directories = ['plugin', 'scripts']

[build.modules]
rjieba = "rjieba"

[build.install.lua]
"rjieba.jieba" = "lua/rjieba/jieba.lua"
